name: continuous integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  tests:
    # runs-on: ubuntu-latest
    # needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    #   - name: Log in to Docker Hub
    #     if: secrets.DOCKER_USERNAME != ''
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build Docker image
    #     run: docker build -t my-flask-api:latest .

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "teste_*.py"


